[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
                "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
                "@uniV3-periphery/contracts/=lib/v3-periphery/contracts/",
                "@uniswap/v3-core/contracts/=lib/v3-core/contracts/",
                "@bytes-utils/=node_modules/solidity-bytes-utils/",
                "@uni-router-v3/contracts/=lib/swap-router-contracts/contracts/",
                "@chainlink/contracts/=lib/chainlink/contracts/"
             ]
             
[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
